### ISSUE TITLE
[Feature] Web Audio-Player for Mobile: jupt to & speed option missing

### ISSUE THREAD

**Issue by 6543** [Linux-For-Everyone/linuxforeveryone#16]
While i was lissening to an episode i noticed its not posivle to jump to a specific point in time without switching to "desctop mode"

You also cant speed up things, I'm usualy listen to videos/audios x1.7 of the normal speed. It would be awesome to get that feature in mobile version.

Thanks

**Comment by vescovaccio** [comment]
> While i was lissening to an episode i noticed its not posivle to jump to a specific point in time without switching to "desctop mode"
> 
> You also cant speed up things, I'm usualy listen to videos/audios x1.7 of the normal speed. It would be awesome to get that feature in mobile version.
> 
> Thanks

Yeah, I noticed that, on Spotify, on a mobile phone, changing the speed while listening caused the app to crash. When reloaded it then worked at the selected speed. I thought this might be an issue with the Spotify app itself. I will try with another Podcast to see if it's like that for all podcasts or just this one.

**Comment by 6543** [comment]
I didnt use spotify i use the html5 player on https://www.linux4everyone.com/46-jeremy-soller-system-76 to be exact ... :)

EDIT: browser is https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/

**Comment by vescovaccio** [comment]
> > While i was lissening to an episode i noticed its not posivle to jump to a specific point in time without switching to "desctop mode"
> > You also cant speed up things, I'm usualy listen to videos/audios x1.7 of the normal speed. It would be awesome to get that feature in mobile version.
> > Thanks
> 
> Yeah, I noticed that, on Spotify, on a mobile phone, changing the speed while listening causes the app to crash. When reloaded it will then work at the selected speed. I thought this might be an issue with the Spotify app itself. I will try with another Podcast to see if it's like that for all podcasts or just this one.

Today, on Spotify on Android, it works totally as expected. Don't know what happened inbetween, but as of now it seems fixed for Android.

**Comment by vescovaccio** [comment]
> I didnt use spotify i use the html5 player on https://www.linux4everyone.com/46-jeremy-soller-system-76 to be exact ... :)
> 
> EDIT: browser is https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/

Yes, you need to select Desktop Site mode to gain access to these controls. That's because the mini-player of the mobile site is different from that of the desktop site. This may change in the future, but I guess this is a "feature request" rather than an "issue", no?

**Comment by 6543** [comment]
well yes, after noticing it works on desktop ... :sweat_smile:

**Comment by LinuxForEveryone** [comment]
Thanks for pointing this out. However, since Fireside.fm is our podcast and website host (for now), I don't have any control over the audio player features. 

Hopefully, that will change in the near future ;-)

**Comment by 6543** [comment]
@KillYourFM thanks for the fast response - may **Funkwhale** :upside_down_face: could be a solution ...

**Comment by LinuxForEveryone** [comment]
I cannot wait to get that awesome funkwhale action started! As far as a web player for the future site, I'm hoping that it can be some kind of custom solution.

-------- Original Message --------
